apiVersion: apps/v1
kind: Deployment
metadata:
  name: catch
  labels:
    app: catch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catch
  template:
    metadata:
      labels:
        app: catch
    spec:
      containers:
        - name: catch
          image: username/catch:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5